name: Build Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make build script executable
      run: chmod +x build/linux.sh

    - name: Build for Linux
      run: ./build/linux.sh
